-- Alta de usuarios: usar scripts (hashean pass y asignan rol)
--
-- Usuario estándar (rol 2):
-- .\scripts\insert-userSSO.ps1 -User jperez -Password "SuClave123" -Name Juan -LastName Perez -Email jperez@mobo.com -Rol 2
--
-- Administrador (rol 1):
-- .\scripts\insert-userSSO.ps1 -User madmin -Password "SuClave123" -Name Maria -LastName Admin -Email madmin@mobo.com -Rol 1
--
-- Consultar roles:
-- SELECT * FROM SSOMOBO.roleSSO;
-- SELECT u.user, u.name, r.nombre AS rol FROM SSOMOBO.userSSO u JOIN SSOMOBO.roleSSO r ON u.rol = r.id;
